// Code generated by curry generator; DO NOT EDIT.
package curry

// region Bind1

// Bind1R binds the first argument of a function of 1, returning one value.
func Bind1R[T0, R any](fn func(T0) R, arg0 T0) func() R {
	return func() R {
		return fn(arg0)
	}
}

// Bind1 binds the first argument of a function of 1, returning no values.
func Bind1[T0 any](fn func(T0), arg0 T0) func() {
	return func() {
		fn(arg0)
	}
}

// Bind1R2 binds the first argument of a function of 1, returning two values.
func Bind1R2[T0, R0, R1 any](fn func(T0) (R0, R1), arg0 T0) func() (R0, R1) {
	return func() (R0, R1) {
		return fn(arg0)
	}
}

// region Bind1S

// Bind1SR binds the first argument of a function of 1, returning one value.
func Bind1SR[T0, R any](fn func(...T0) R, arg0 ...T0) func() R {
	return func() R {
		return fn(arg0...)
	}
}

// Bind1S binds the first argument of a function of 1, returning no values.
func Bind1S[T0 any](fn func(...T0), arg0 ...T0) func() {
	return func() {
		fn(arg0...)
	}
}

// Bind1SR2 binds the first argument of a function of 1, returning one value.
func Bind1SR2[T0, R0, R1 any](fn func(...T0) (R0, R1), arg0 ...T0) func() (R0, R1) {
	return func() (R0, R1) {
		return fn(arg0...)
	}
}

// region BindFirstOf2

// BindFirstOf2R binds the first argument of a function of 2, returning one value.
func BindFirstOf2R[T0, T1, R any](fn func(T0, T1) R, arg0 T0) func(T1) R {
	return Head2R(fn)(arg0)
}

// BindFirstOf2 binds the first argument of a function of 2, returning no values.
func BindFirstOf2[T0, T1 any](fn func(T0, T1), arg0 T0) func(T1) {
	return Head2(fn)(arg0)
}

// BindFirstOf2R2 binds the first argument of a function of 2, returning two values.
func BindFirstOf2R2[T0, T1, R0, R1 any](fn func(T0, T1) (R0, R1), arg0 T0) func(T1) (R0, R1) {
	return Head2R2(fn)(arg0)
}

// region BindFirstOf2S

// BindFirstOf2SR binds the first argument of a function of 2, returning one value.
func BindFirstOf2SR[T0, T1, R any](fn func(T0, ...T1) R, arg0 T0) func(...T1) R {
	return Head2SR(fn)(arg0)
}

// BindFirstOf2S binds the first argument of a function of 2, returning no values.
func BindFirstOf2S[T0, T1 any](fn func(T0, ...T1), arg0 T0) func(...T1) {
	return Head2S(fn)(arg0)
}

// BindFirstOf2SR2 binds the first argument of a function of 2, returning one value.
func BindFirstOf2SR2[T0, T1, R0, R1 any](fn func(T0, ...T1) (R0, R1), arg0 T0) func(...T1) (R0, R1) {
	return Head2SR2(fn)(arg0)
}

// region BindLastOf2

// BindLastOf2R binds the last argument of a function of 2, returning one value.
func BindLastOf2R[T0, T1, R any](fn func(T0, T1) R, arg1 T1) func(T0) R {
	return func(arg0 T0) R {
		return fn(arg0, arg1)
	}
}

// BindLastOf2 binds the last argument of a function of 2, returning no values.
func BindLastOf2[T0, T1 any](fn func(T0, T1), arg1 T1) func(T0) {
	return func(arg0 T0) {
		fn(arg0, arg1)
	}
}

// BindLastOf2R2 binds the last ellipsis argument of a function of 2, returning two values.
func BindLastOf2R2[T0, T1, R0, R1 any](fn func(T0, T1) (R0, R1), arg1 T1) func(T0) (R0, R1) {
	return func(arg0 T0) (R0, R1) {
		return fn(arg0, arg1)
	}
}

// region BindLastOf2S

// BindLastOf2SR binds the last ellipsis argument of a function of 2, returning one value.
func BindLastOf2SR[T0, T1, R any](fn func(T0, ...T1) R, arg1 ...T1) func(T0) R {
	return func(arg0 T0) R {
		return fn(arg0, arg1...)
	}
}

// BindLastOf2S binds the last ellipsis argument of a function of 2, returning no values.
func BindLastOf2S[T0, T1 any](fn func(T0, ...T1), arg1 ...T1) func(T0) {
	return func(arg0 T0) {
		fn(arg0, arg1...)
	}
}

// BindLastOf2SR2 binds the last ellipsis argument of a function of 2, returning two values.
func BindLastOf2SR2[T0, T1, R0, R1 any](fn func(T0, ...T1) (R0, R1), arg1 ...T1) func(T0) (R0, R1) {
	return func(arg0 T0) (R0, R1) {
		return fn(arg0, arg1...)
	}
}

// region BindFirstOf3

// BindFirstOf3R binds the first argument of a function of 3, returning one value.
func BindFirstOf3R[T0, T1, T2, R any](fn func(T0, T1, T2) R, arg0 T0) func(T1, T2) R {
	return Head3R(fn)(arg0)
}

// BindFirstOf3 binds the first argument of a function of 3, returning no values.
func BindFirstOf3[T0, T1, T2 any](fn func(T0, T1, T2), arg0 T0) func(T1, T2) {
	return Head3(fn)(arg0)
}

// BindFirstOf3R2 binds the first argument of a function of 3, returning two values.
func BindFirstOf3R2[T0, T1, T2, R0, R1 any](fn func(T0, T1, T2) (R0, R1), arg0 T0) func(T1, T2) (R0, R1) {
	return Head3R2(fn)(arg0)
}

// region BindFirstOf3S

// BindFirstOf3SR binds the first argument of a function of 3, returning one value.
func BindFirstOf3SR[T0, T1, T2, R any](fn func(T0, T1, ...T2) R, arg0 T0) func(T1, ...T2) R {
	return Head3SR(fn)(arg0)
}

// BindFirstOf3S binds the first argument of a function of 3, returning no values.
func BindFirstOf3S[T0, T1, T2 any](fn func(T0, T1, ...T2), arg0 T0) func(T1, ...T2) {
	return Head3S(fn)(arg0)
}

// BindFirstOf3SR2 binds the first argument of a function of 3, returning one value.
func BindFirstOf3SR2[T0, T1, T2, R0, R1 any](fn func(T0, T1, ...T2) (R0, R1), arg0 T0) func(T1, ...T2) (R0, R1) {
	return Head3SR2(fn)(arg0)
}

// region BindLastOf3

// BindLastOf3R binds the last argument of a function of 3, returning one value.
func BindLastOf3R[T0, T1, T2, R any](fn func(T0, T1, T2) R, arg2 T2) func(T0, T1) R {
	return func(arg0 T0, arg1 T1) R {
		return fn(arg0, arg1, arg2)
	}
}

// BindLastOf3 binds the last argument of a function of 3, returning no values.
func BindLastOf3[T0, T1, T2 any](fn func(T0, T1, T2), arg2 T2) func(T0, T1) {
	return func(arg0 T0, arg1 T1) {
		fn(arg0, arg1, arg2)
	}
}

// BindLastOf3R2 binds the last ellipsis argument of a function of 3, returning two values.
func BindLastOf3R2[T0, T1, T2, R0, R1 any](fn func(T0, T1, T2) (R0, R1), arg2 T2) func(T0, T1) (R0, R1) {
	return func(arg0 T0, arg1 T1) (R0, R1) {
		return fn(arg0, arg1, arg2)
	}
}

// region BindLastOf3S

// BindLastOf3SR binds the last ellipsis argument of a function of 3, returning one value.
func BindLastOf3SR[T0, T1, T2, R any](fn func(T0, T1, ...T2) R, arg2 ...T2) func(T0, T1) R {
	return func(arg0 T0, arg1 T1) R {
		return fn(arg0, arg1, arg2...)
	}
}

// BindLastOf3S binds the last ellipsis argument of a function of 3, returning no values.
func BindLastOf3S[T0, T1, T2 any](fn func(T0, T1, ...T2), arg2 ...T2) func(T0, T1) {
	return func(arg0 T0, arg1 T1) {
		fn(arg0, arg1, arg2...)
	}
}

// BindLastOf3SR2 binds the last ellipsis argument of a function of 3, returning two values.
func BindLastOf3SR2[T0, T1, T2, R0, R1 any](fn func(T0, T1, ...T2) (R0, R1), arg2 ...T2) func(T0, T1) (R0, R1) {
	return func(arg0 T0, arg1 T1) (R0, R1) {
		return fn(arg0, arg1, arg2...)
	}
}

// region BindFirstOf4

// BindFirstOf4R binds the first argument of a function of 4, returning one value.
func BindFirstOf4R[T0, T1, T2, T3, R any](fn func(T0, T1, T2, T3) R, arg0 T0) func(T1, T2, T3) R {
	return Head4R(fn)(arg0)
}

// BindFirstOf4 binds the first argument of a function of 4, returning no values.
func BindFirstOf4[T0, T1, T2, T3 any](fn func(T0, T1, T2, T3), arg0 T0) func(T1, T2, T3) {
	return Head4(fn)(arg0)
}

// BindFirstOf4R2 binds the first argument of a function of 4, returning two values.
func BindFirstOf4R2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, T3) (R0, R1), arg0 T0) func(T1, T2, T3) (R0, R1) {
	return Head4R2(fn)(arg0)
}

// region BindFirstOf4S

// BindFirstOf4SR binds the first argument of a function of 4, returning one value.
func BindFirstOf4SR[T0, T1, T2, T3, R any](fn func(T0, T1, T2, ...T3) R, arg0 T0) func(T1, T2, ...T3) R {
	return Head4SR(fn)(arg0)
}

// BindFirstOf4S binds the first argument of a function of 4, returning no values.
func BindFirstOf4S[T0, T1, T2, T3 any](fn func(T0, T1, T2, ...T3), arg0 T0) func(T1, T2, ...T3) {
	return Head4S(fn)(arg0)
}

// BindFirstOf4SR2 binds the first argument of a function of 4, returning one value.
func BindFirstOf4SR2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, ...T3) (R0, R1), arg0 T0) func(T1, T2, ...T3) (R0, R1) {
	return Head4SR2(fn)(arg0)
}

// region BindLastOf4

// BindLastOf4R binds the last argument of a function of 4, returning one value.
func BindLastOf4R[T0, T1, T2, T3, R any](fn func(T0, T1, T2, T3) R, arg3 T3) func(T0, T1, T2) R {
	return func(arg0 T0, arg1 T1, arg2 T2) R {
		return fn(arg0, arg1, arg2, arg3)
	}
}

// BindLastOf4 binds the last argument of a function of 4, returning no values.
func BindLastOf4[T0, T1, T2, T3 any](fn func(T0, T1, T2, T3), arg3 T3) func(T0, T1, T2) {
	return func(arg0 T0, arg1 T1, arg2 T2) {
		fn(arg0, arg1, arg2, arg3)
	}
}

// BindLastOf4R2 binds the last ellipsis argument of a function of 4, returning two values.
func BindLastOf4R2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, T3) (R0, R1), arg3 T3) func(T0, T1, T2) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2) (R0, R1) {
		return fn(arg0, arg1, arg2, arg3)
	}
}

// region BindLastOf4S

// BindLastOf4SR binds the last ellipsis argument of a function of 4, returning one value.
func BindLastOf4SR[T0, T1, T2, T3, R any](fn func(T0, T1, T2, ...T3) R, arg3 ...T3) func(T0, T1, T2) R {
	return func(arg0 T0, arg1 T1, arg2 T2) R {
		return fn(arg0, arg1, arg2, arg3...)
	}
}

// BindLastOf4S binds the last ellipsis argument of a function of 4, returning no values.
func BindLastOf4S[T0, T1, T2, T3 any](fn func(T0, T1, T2, ...T3), arg3 ...T3) func(T0, T1, T2) {
	return func(arg0 T0, arg1 T1, arg2 T2) {
		fn(arg0, arg1, arg2, arg3...)
	}
}

// BindLastOf4SR2 binds the last ellipsis argument of a function of 4, returning two values.
func BindLastOf4SR2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, ...T3) (R0, R1), arg3 ...T3) func(T0, T1, T2) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2) (R0, R1) {
		return fn(arg0, arg1, arg2, arg3...)
	}
}

// region BindFirstOf5

// BindFirstOf5R binds the first argument of a function of 5, returning one value.
func BindFirstOf5R[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, T4) R, arg0 T0) func(T1, T2, T3, T4) R {
	return Head5R(fn)(arg0)
}

// BindFirstOf5 binds the first argument of a function of 5, returning no values.
func BindFirstOf5[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, T4), arg0 T0) func(T1, T2, T3, T4) {
	return Head5(fn)(arg0)
}

// BindFirstOf5R2 binds the first argument of a function of 5, returning two values.
func BindFirstOf5R2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, T4) (R0, R1), arg0 T0) func(T1, T2, T3, T4) (R0, R1) {
	return Head5R2(fn)(arg0)
}

// region BindFirstOf5S

// BindFirstOf5SR binds the first argument of a function of 5, returning one value.
func BindFirstOf5SR[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, ...T4) R, arg0 T0) func(T1, T2, T3, ...T4) R {
	return Head5SR(fn)(arg0)
}

// BindFirstOf5S binds the first argument of a function of 5, returning no values.
func BindFirstOf5S[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, ...T4), arg0 T0) func(T1, T2, T3, ...T4) {
	return Head5S(fn)(arg0)
}

// BindFirstOf5SR2 binds the first argument of a function of 5, returning one value.
func BindFirstOf5SR2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, ...T4) (R0, R1), arg0 T0) func(T1, T2, T3, ...T4) (R0, R1) {
	return Head5SR2(fn)(arg0)
}

// region BindLastOf5

// BindLastOf5R binds the last argument of a function of 5, returning one value.
func BindLastOf5R[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, T4) R, arg4 T4) func(T0, T1, T2, T3) R {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) R {
		return fn(arg0, arg1, arg2, arg3, arg4)
	}
}

// BindLastOf5 binds the last argument of a function of 5, returning no values.
func BindLastOf5[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, T4), arg4 T4) func(T0, T1, T2, T3) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) {
		fn(arg0, arg1, arg2, arg3, arg4)
	}
}

// BindLastOf5R2 binds the last ellipsis argument of a function of 5, returning two values.
func BindLastOf5R2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, T4) (R0, R1), arg4 T4) func(T0, T1, T2, T3) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) (R0, R1) {
		return fn(arg0, arg1, arg2, arg3, arg4)
	}
}

// region BindLastOf5S

// BindLastOf5SR binds the last ellipsis argument of a function of 5, returning one value.
func BindLastOf5SR[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, ...T4) R, arg4 ...T4) func(T0, T1, T2, T3) R {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) R {
		return fn(arg0, arg1, arg2, arg3, arg4...)
	}
}

// BindLastOf5S binds the last ellipsis argument of a function of 5, returning no values.
func BindLastOf5S[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, ...T4), arg4 ...T4) func(T0, T1, T2, T3) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) {
		fn(arg0, arg1, arg2, arg3, arg4...)
	}
}

// BindLastOf5SR2 binds the last ellipsis argument of a function of 5, returning two values.
func BindLastOf5SR2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, ...T4) (R0, R1), arg4 ...T4) func(T0, T1, T2, T3) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) (R0, R1) {
		return fn(arg0, arg1, arg2, arg3, arg4...)
	}
}
