// Code generated by curry generator; DO NOT EDIT.
package curry

// region F2

// F2R curries a function of 2 parameter(s), returning one value.
func F2R[T0, T1, R any](fn func(T0, T1) R) func(T0) func(T1) R {
	return Head2R(fn)
}

// F2 curries a function of 2 parameter(s), returning no values.
func F2[T0, T1 any](fn func(T0, T1)) func(T0) func(T1) {
	return Head2(fn)
}

// F2R2 curries a function of 2 parameter(s), returning two values.
func F2R2[T0, T1, R0, R1 any](fn func(T0, T1) (R0, R1)) func(T0) func(T1) (R0, R1) {
	return Head2R2(fn)
}

// F2SR curries a function of 2 parameter(s), returning one value.
func F2SR[T0, T1, R any](fn func(T0, ...T1) R) func(T0) func(...T1) R {
	return Head2SR(fn)
}

// F2S curries a function of 2 parameter(s), returning no values.
func F2S[T0, T1 any](fn func(T0, ...T1)) func(T0) func(...T1) {
	return Head2S(fn)
}

// F2SR2 curries a function of 2 parameter(s), returning two values.
func F2SR2[T0, T1, R0, R1 any](fn func(T0, ...T1) (R0, R1)) func(T0) func(...T1) (R0, R1) {
	return Head2SR2(fn)
}

// region F3

// F3R curries a function of 3 parameter(s), returning one value.
func F3R[T0, T1, T2, R any](fn func(T0, T1, T2) R) func(T0) func(T1) func(T2) R {
	return func(arg0 T0) func(T1) func(T2) R {
		return F2R(Head3R(fn)(arg0))
	}
}

// F3 curries a function of 3 parameter(s), returning no values.
func F3[T0, T1, T2 any](fn func(T0, T1, T2)) func(T0) func(T1) func(T2) {
	return func(arg0 T0) func(T1) func(T2) {
		return F2(Head3(fn)(arg0))
	}
}

// F3R2 curries a function of 3 parameter(s), returning two values.
func F3R2[T0, T1, T2, R0, R1 any](fn func(T0, T1, T2) (R0, R1)) func(T0) func(T1) func(T2) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) (R0, R1) {
		return F2R2(Head3R2(fn)(arg0))
	}
}

// F3SR curries a function of 3 parameter(s), returning one value.
func F3SR[T0, T1, T2, R any](fn func(T0, T1, ...T2) R) func(T0) func(T1) func(...T2) R {
	return func(arg0 T0) func(T1) func(...T2) R {
		return F2SR(Head3SR(fn)(arg0))
	}
}

// F3S curries a function of 3 parameter(s), returning no values.
func F3S[T0, T1, T2 any](fn func(T0, T1, ...T2)) func(T0) func(T1) func(...T2) {
	return func(arg0 T0) func(T1) func(...T2) {
		return F2S(Head3S(fn)(arg0))
	}
}

// F3SR2 curries a function of 3 parameter(s), returning two values.
func F3SR2[T0, T1, T2, R0, R1 any](fn func(T0, T1, ...T2) (R0, R1)) func(T0) func(T1) func(...T2) (R0, R1) {
	return func(arg0 T0) func(T1) func(...T2) (R0, R1) {
		return F2SR2(Head3SR2(fn)(arg0))
	}
}

// region F4

// F4R curries a function of 4 parameter(s), returning one value.
func F4R[T0, T1, T2, T3, R any](fn func(T0, T1, T2, T3) R) func(T0) func(T1) func(T2) func(T3) R {
	return func(arg0 T0) func(T1) func(T2) func(T3) R {
		return F3R(Head4R(fn)(arg0))
	}
}

// F4 curries a function of 4 parameter(s), returning no values.
func F4[T0, T1, T2, T3 any](fn func(T0, T1, T2, T3)) func(T0) func(T1) func(T2) func(T3) {
	return func(arg0 T0) func(T1) func(T2) func(T3) {
		return F3(Head4(fn)(arg0))
	}
}

// F4R2 curries a function of 4 parameter(s), returning two values.
func F4R2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, T3) (R0, R1)) func(T0) func(T1) func(T2) func(T3) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(T3) (R0, R1) {
		return F3R2(Head4R2(fn)(arg0))
	}
}

// F4SR curries a function of 4 parameter(s), returning one value.
func F4SR[T0, T1, T2, T3, R any](fn func(T0, T1, T2, ...T3) R) func(T0) func(T1) func(T2) func(...T3) R {
	return func(arg0 T0) func(T1) func(T2) func(...T3) R {
		return F3SR(Head4SR(fn)(arg0))
	}
}

// F4S curries a function of 4 parameter(s), returning no values.
func F4S[T0, T1, T2, T3 any](fn func(T0, T1, T2, ...T3)) func(T0) func(T1) func(T2) func(...T3) {
	return func(arg0 T0) func(T1) func(T2) func(...T3) {
		return F3S(Head4S(fn)(arg0))
	}
}

// F4SR2 curries a function of 4 parameter(s), returning two values.
func F4SR2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, ...T3) (R0, R1)) func(T0) func(T1) func(T2) func(...T3) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(...T3) (R0, R1) {
		return F3SR2(Head4SR2(fn)(arg0))
	}
}

// region F5

// F5R curries a function of 5 parameter(s), returning one value.
func F5R[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, T4) R) func(T0) func(T1) func(T2) func(T3) func(T4) R {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(T4) R {
		return F4R(Head5R(fn)(arg0))
	}
}

// F5 curries a function of 5 parameter(s), returning no values.
func F5[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, T4)) func(T0) func(T1) func(T2) func(T3) func(T4) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(T4) {
		return F4(Head5(fn)(arg0))
	}
}

// F5R2 curries a function of 5 parameter(s), returning two values.
func F5R2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, T4) (R0, R1)) func(T0) func(T1) func(T2) func(T3) func(T4) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(T4) (R0, R1) {
		return F4R2(Head5R2(fn)(arg0))
	}
}

// F5SR curries a function of 5 parameter(s), returning one value.
func F5SR[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, ...T4) R) func(T0) func(T1) func(T2) func(T3) func(...T4) R {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(...T4) R {
		return F4SR(Head5SR(fn)(arg0))
	}
}

// F5S curries a function of 5 parameter(s), returning no values.
func F5S[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, ...T4)) func(T0) func(T1) func(T2) func(T3) func(...T4) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(...T4) {
		return F4S(Head5S(fn)(arg0))
	}
}

// F5SR2 curries a function of 5 parameter(s), returning two values.
func F5SR2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, ...T4) (R0, R1)) func(T0) func(T1) func(T2) func(T3) func(...T4) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(...T4) (R0, R1) {
		return F4SR2(Head5SR2(fn)(arg0))
	}
}
