// Code generated by curry generator; DO NOT EDIT.
package curry

// region: Curry2

// Curry2R curries a function of 2 parameter(s), returning one value.
func Curry2R[T0, T1, R any](fn func(T0, T1) R) func(T0) func(T1) R {
	return Head2R(fn)
}

// Curry2 curries a function of 2 parameter(s), returning no values.
func Curry2[T0, T1 any](fn func(T0, T1)) func(T0) func(T1) {
	return Head2(fn)
}

// Curry2R2 curries a function of 2 parameter(s), returning two values.
func Curry2R2[T0, T1, R0, R1 any](fn func(T0, T1) (R0, R1)) func(T0) func(T1) (R0, R1) {
	return Head2R2(fn)
}

// Curry2SR curries a function of 2 parameter(s), returning one value.
func Curry2SR[T0, T1, R any](fn func(T0, ...T1) R) func(T0) func(...T1) R {
	return Head2SR(fn)
}

// Curry2S curries a function of 2 parameter(s), returning no values.
func Curry2S[T0, T1 any](fn func(T0, ...T1)) func(T0) func(...T1) {
	return Head2S(fn)
}

// Curry2SR2 curries a function of 2 parameter(s), returning two values.
func Curry2SR2[T0, T1, R0, R1 any](fn func(T0, ...T1) (R0, R1)) func(T0) func(...T1) (R0, R1) {
	return Head2SR2(fn)
}

// region: Curry3

// Curry3R curries a function of 3 parameter(s), returning one value.
func Curry3R[T0, T1, T2, R any](fn func(T0, T1, T2) R) func(T0) func(T1) func(T2) R {
	return func(arg0 T0) func(T1) func(T2) R {
		return Curry2R(Head3R(fn)(arg0))
	}
}

// Curry3 curries a function of 3 parameter(s), returning no values.
func Curry3[T0, T1, T2 any](fn func(T0, T1, T2)) func(T0) func(T1) func(T2) {
	return func(arg0 T0) func(T1) func(T2) {
		return Curry2(Head3(fn)(arg0))
	}
}

// Curry3R2 curries a function of 3 parameter(s), returning two values.
func Curry3R2[T0, T1, T2, R0, R1 any](fn func(T0, T1, T2) (R0, R1)) func(T0) func(T1) func(T2) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) (R0, R1) {
		return Curry2R2(Head3R2(fn)(arg0))
	}
}

// Curry3SR curries a function of 3 parameter(s), returning one value.
func Curry3SR[T0, T1, T2, R any](fn func(T0, T1, ...T2) R) func(T0) func(T1) func(...T2) R {
	return func(arg0 T0) func(T1) func(...T2) R {
		return Curry2SR(Head3SR(fn)(arg0))
	}
}

// Curry3S curries a function of 3 parameter(s), returning no values.
func Curry3S[T0, T1, T2 any](fn func(T0, T1, ...T2)) func(T0) func(T1) func(...T2) {
	return func(arg0 T0) func(T1) func(...T2) {
		return Curry2S(Head3S(fn)(arg0))
	}
}

// Curry3SR2 curries a function of 3 parameter(s), returning two values.
func Curry3SR2[T0, T1, T2, R0, R1 any](fn func(T0, T1, ...T2) (R0, R1)) func(T0) func(T1) func(...T2) (R0, R1) {
	return func(arg0 T0) func(T1) func(...T2) (R0, R1) {
		return Curry2SR2(Head3SR2(fn)(arg0))
	}
}

// region: Curry4

// Curry4R curries a function of 4 parameter(s), returning one value.
func Curry4R[T0, T1, T2, T3, R any](fn func(T0, T1, T2, T3) R) func(T0) func(T1) func(T2) func(T3) R {
	return func(arg0 T0) func(T1) func(T2) func(T3) R {
		return Curry3R(Head4R(fn)(arg0))
	}
}

// Curry4 curries a function of 4 parameter(s), returning no values.
func Curry4[T0, T1, T2, T3 any](fn func(T0, T1, T2, T3)) func(T0) func(T1) func(T2) func(T3) {
	return func(arg0 T0) func(T1) func(T2) func(T3) {
		return Curry3(Head4(fn)(arg0))
	}
}

// Curry4R2 curries a function of 4 parameter(s), returning two values.
func Curry4R2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, T3) (R0, R1)) func(T0) func(T1) func(T2) func(T3) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(T3) (R0, R1) {
		return Curry3R2(Head4R2(fn)(arg0))
	}
}

// Curry4SR curries a function of 4 parameter(s), returning one value.
func Curry4SR[T0, T1, T2, T3, R any](fn func(T0, T1, T2, ...T3) R) func(T0) func(T1) func(T2) func(...T3) R {
	return func(arg0 T0) func(T1) func(T2) func(...T3) R {
		return Curry3SR(Head4SR(fn)(arg0))
	}
}

// Curry4S curries a function of 4 parameter(s), returning no values.
func Curry4S[T0, T1, T2, T3 any](fn func(T0, T1, T2, ...T3)) func(T0) func(T1) func(T2) func(...T3) {
	return func(arg0 T0) func(T1) func(T2) func(...T3) {
		return Curry3S(Head4S(fn)(arg0))
	}
}

// Curry4SR2 curries a function of 4 parameter(s), returning two values.
func Curry4SR2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, ...T3) (R0, R1)) func(T0) func(T1) func(T2) func(...T3) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(...T3) (R0, R1) {
		return Curry3SR2(Head4SR2(fn)(arg0))
	}
}

// region: Curry5

// Curry5R curries a function of 5 parameter(s), returning one value.
func Curry5R[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, T4) R) func(T0) func(T1) func(T2) func(T3) func(T4) R {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(T4) R {
		return Curry4R(Head5R(fn)(arg0))
	}
}

// Curry5 curries a function of 5 parameter(s), returning no values.
func Curry5[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, T4)) func(T0) func(T1) func(T2) func(T3) func(T4) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(T4) {
		return Curry4(Head5(fn)(arg0))
	}
}

// Curry5R2 curries a function of 5 parameter(s), returning two values.
func Curry5R2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, T4) (R0, R1)) func(T0) func(T1) func(T2) func(T3) func(T4) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(T4) (R0, R1) {
		return Curry4R2(Head5R2(fn)(arg0))
	}
}

// Curry5SR curries a function of 5 parameter(s), returning one value.
func Curry5SR[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, ...T4) R) func(T0) func(T1) func(T2) func(T3) func(...T4) R {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(...T4) R {
		return Curry4SR(Head5SR(fn)(arg0))
	}
}

// Curry5S curries a function of 5 parameter(s), returning no values.
func Curry5S[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, ...T4)) func(T0) func(T1) func(T2) func(T3) func(...T4) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(...T4) {
		return Curry4S(Head5S(fn)(arg0))
	}
}

// Curry5SR2 curries a function of 5 parameter(s), returning two values.
func Curry5SR2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, ...T4) (R0, R1)) func(T0) func(T1) func(T2) func(T3) func(...T4) (R0, R1) {
	return func(arg0 T0) func(T1) func(T2) func(T3) func(...T4) (R0, R1) {
		return Curry4SR2(Head5SR2(fn)(arg0))
	}
}
