// Code generated by curry generator; DO NOT EDIT.
package curry

// regionDrop*Of1

// DropFirstOf1 drops the first value from a tuple of 1.
func DropFirstOf1[T0 any](_ T0) {
	return
}

// regionDrop*Of2

// DropFirstOf2 drops the first value from a tuple of 2.
func DropFirstOf2[T0, T1 any](_ T0, arg1 T1) T1 {
	return arg1
}

// DropLastOf2 drops the last value from a tuple of 2.
func DropLastOf2[T0, T1 any](arg0 T0, arg1 T1) T0 {
	return arg0
}

// regionDrop*Of3

// DropFirstOf3 drops the first value from a tuple of 3.
func DropFirstOf3[T0, T1, T2 any](_ T0, arg1 T1, arg2 T2) (T1, T2) {
	return arg1, arg2
}

// DropLastOf3 drops the last value from a tuple of 3.
func DropLastOf3[T0, T1, T2 any](arg0 T0, arg1 T1, arg2 T2) (T0, T1) {
	return arg0, arg1
}

// regionDrop*Of4

// DropFirstOf4 drops the first value from a tuple of 4.
func DropFirstOf4[T0, T1, T2, T3 any](_ T0, arg1 T1, arg2 T2, arg3 T3) (T1, T2, T3) {
	return arg1, arg2, arg3
}

// DropLastOf4 drops the last value from a tuple of 4.
func DropLastOf4[T0, T1, T2, T3 any](arg0 T0, arg1 T1, arg2 T2, arg3 T3) (T0, T1, T2) {
	return arg0, arg1, arg2
}

// regionDrop*Of5

// DropFirstOf5 drops the first value from a tuple of 5.
func DropFirstOf5[T0, T1, T2, T3, T4 any](_ T0, arg1 T1, arg2 T2, arg3 T3, arg4 T4) (T1, T2, T3, T4) {
	return arg1, arg2, arg3, arg4
}

// DropLastOf5 drops the last value from a tuple of 5.
func DropLastOf5[T0, T1, T2, T3, T4 any](arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 T4) (T0, T1, T2, T3) {
	return arg0, arg1, arg2, arg3
}
