// Code generated by curry generator; DO NOT EDIT.
package curry

// region: 0
type FnSig0R[R any] struct {
	RV0 R
}

type FnSig0R2[R0, R1 any] struct {
	RV0 R0
	RV1 R1
}

func Signature0R[R any](fn func() R) (s FnSig0R[R]) {
	return
}

func Signature0R2[R0, R1 any](fn func() (R0, R1)) (s FnSig0R2[R0, R1]) {
	return
}

// region: 1

type FnSig1[T0 any] struct {
	Arg0 T0
}

type FnSig1R[T0, R any] struct {
	FnSig1[T0]
    FnSig0R[R]
}

type FnSig1R2[T0, R0, R1 any] struct {
	FnSig1[T0]
	FnSig0R2[R0, R1]
}

func Signature1R[T0, R any](fn func(T0) R) (s FnSig1R[T0, R]) {
	return
}

func Signature1[T0 any](fn func(T0)) (s FnSig1[T0]) {
	return
}

func Signature1R2[T0, R0, R1 any](fn func(T0) (R0, R1)) (s FnSig1R2[T0, R0, R1]) {
	return
}

// region: 2

type FnSig2[T0, T1 any] struct {
	FnSig1[T0]
	Arg1 T1
}

type FnSig2R[T0, T1, R any] struct {
	FnSig2[T0, T1]
    FnSig0R[R]
}

type FnSig2R2[T0, T1, R0, R1 any] struct {
	FnSig2[T0, T1]
	FnSig0R2[R0, R1]
}

func Signature2R[T0, T1, R any](fn func(T0, T1) R) (s FnSig2R[T0, T1, R]) {
	return
}

func Signature2[T0, T1 any](fn func(T0, T1)) (s FnSig2[T0, T1]) {
	return
}

func Signature2R2[T0, T1, R0, R1 any](fn func(T0, T1) (R0, R1)) (s FnSig2R2[T0, T1, R0, R1]) {
	return
}

// region: 3

type FnSig3[T0, T1, T2 any] struct {
	FnSig2[T0, T1]
	Arg2 T2
}

type FnSig3R[T0, T1, T2, R any] struct {
	FnSig3[T0, T1, T2]
    FnSig0R[R]
}

type FnSig3R2[T0, T1, T2, R0, R1 any] struct {
	FnSig3[T0, T1, T2]
	FnSig0R2[R0, R1]
}

func Signature3R[T0, T1, T2, R any](fn func(T0, T1, T2) R) (s FnSig3R[T0, T1, T2, R]) {
	return
}

func Signature3[T0, T1, T2 any](fn func(T0, T1, T2)) (s FnSig3[T0, T1, T2]) {
	return
}

func Signature3R2[T0, T1, T2, R0, R1 any](fn func(T0, T1, T2) (R0, R1)) (s FnSig3R2[T0, T1, T2, R0, R1]) {
	return
}

// region: 4

type FnSig4[T0, T1, T2, T3 any] struct {
	FnSig3[T0, T1, T2]
	Arg3 T3
}

type FnSig4R[T0, T1, T2, T3, R any] struct {
	FnSig4[T0, T1, T2, T3]
    FnSig0R[R]
}

type FnSig4R2[T0, T1, T2, T3, R0, R1 any] struct {
	FnSig4[T0, T1, T2, T3]
	FnSig0R2[R0, R1]
}

func Signature4R[T0, T1, T2, T3, R any](fn func(T0, T1, T2, T3) R) (s FnSig4R[T0, T1, T2, T3, R]) {
	return
}

func Signature4[T0, T1, T2, T3 any](fn func(T0, T1, T2, T3)) (s FnSig4[T0, T1, T2, T3]) {
	return
}

func Signature4R2[T0, T1, T2, T3, R0, R1 any](fn func(T0, T1, T2, T3) (R0, R1)) (s FnSig4R2[T0, T1, T2, T3, R0, R1]) {
	return
}

// region: 5

type FnSig5[T0, T1, T2, T3, T4 any] struct {
	FnSig4[T0, T1, T2, T3]
	Arg4 T4
}

type FnSig5R[T0, T1, T2, T3, T4, R any] struct {
	FnSig5[T0, T1, T2, T3, T4]
    FnSig0R[R]
}

type FnSig5R2[T0, T1, T2, T3, T4, R0, R1 any] struct {
	FnSig5[T0, T1, T2, T3, T4]
	FnSig0R2[R0, R1]
}

func Signature5R[T0, T1, T2, T3, T4, R any](fn func(T0, T1, T2, T3, T4) R) (s FnSig5R[T0, T1, T2, T3, T4, R]) {
	return
}

func Signature5[T0, T1, T2, T3, T4 any](fn func(T0, T1, T2, T3, T4)) (s FnSig5[T0, T1, T2, T3, T4]) {
	return
}

func Signature5R2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0, T1, T2, T3, T4) (R0, R1)) (s FnSig5R2[T0, T1, T2, T3, T4, R0, R1]) {
	return
}