// Code generated by curry generator; DO NOT EDIT.
package curry

// region 2

// Un2R transforms a curried function with 2 parameter(s) back into its original form.
func Un2R[T0, T1, R any](fn func(T0) func(T1) R) func(T0, T1) R {
	return func(arg0 T0, arg1 T1) R {
		return fn(arg0)(arg1)
	}
}

// Un2 transforms a curried function with 2 parameter(s) back into its original form.
func Un2[T0, T1 any](fn func(T0) func(T1)) func(T0, T1) {
	return func(arg0 T0, arg1 T1) {
		fn(arg0)(arg1)
	}
}

// Un2R2 transforms a curried function with 2 parameter(s) back into its original form.
func Un2R2[T0, T1, R0, R1 any](fn func(T0) func(T1) (R0, R1)) func(T0, T1) (R0, R1) {
	return func(arg0 T0, arg1 T1) (R0, R1) {
		return fn(arg0)(arg1)
	}
}

// Un2SR transforms a curried function with 2 parameter(s) back into its original form.
func Un2SR[T0, T1, R any](fn func(T0) func(...T1) R) func(T0, ...T1) R {
	return func(arg0 T0, arg1 ...T1) R {
		return fn(arg0)(arg1...)
	}
}

// Un2S transforms a curried function with 2 parameter(s) back into its original form.
func Un2S[T0, T1 any](fn func(T0) func(...T1)) func(T0, ...T1) {
	return func(arg0 T0, arg1 ...T1) {
		fn(arg0)(arg1...)
	}
}

// Un2SR2 transforms a curried function with 2 parameter(s) back into its original form.
func Un2SR2[T0, T1, R0, R1 any](fn func(T0) func(...T1) (R0, R1)) func(T0, ...T1) (R0, R1) {
	return func(arg0 T0, arg1 ...T1) (R0, R1) {
		return fn(arg0)(arg1...)
	}
}

// region 3

// Un3R transforms a curried function with 3 parameter(s) back into its original form.
func Un3R[T0, T1, T2, R any](fn func(T0) func(T1) func(T2) R) func(T0, T1, T2) R {
	return func(arg0 T0, arg1 T1, arg2 T2) R {
		return fn(arg0)(arg1)(arg2)
	}
}

// Un3 transforms a curried function with 3 parameter(s) back into its original form.
func Un3[T0, T1, T2 any](fn func(T0) func(T1) func(T2)) func(T0, T1, T2) {
	return func(arg0 T0, arg1 T1, arg2 T2) {
		fn(arg0)(arg1)(arg2)
	}
}

// Un3R2 transforms a curried function with 3 parameter(s) back into its original form.
func Un3R2[T0, T1, T2, R0, R1 any](fn func(T0) func(T1) func(T2) (R0, R1)) func(T0, T1, T2) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2) (R0, R1) {
		return fn(arg0)(arg1)(arg2)
	}
}

// Un3SR transforms a curried function with 3 parameter(s) back into its original form.
func Un3SR[T0, T1, T2, R any](fn func(T0) func(T1) func(...T2) R) func(T0, T1, ...T2) R {
	return func(arg0 T0, arg1 T1, arg2 ...T2) R {
		return fn(arg0)(arg1)(arg2...)
	}
}

// Un3S transforms a curried function with 3 parameter(s) back into its original form.
func Un3S[T0, T1, T2 any](fn func(T0) func(T1) func(...T2)) func(T0, T1, ...T2) {
	return func(arg0 T0, arg1 T1, arg2 ...T2) {
		fn(arg0)(arg1)(arg2...)
	}
}

// Un3SR2 transforms a curried function with 3 parameter(s) back into its original form.
func Un3SR2[T0, T1, T2, R0, R1 any](fn func(T0) func(T1) func(...T2) (R0, R1)) func(T0, T1, ...T2) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 ...T2) (R0, R1) {
		return fn(arg0)(arg1)(arg2...)
	}
}

// region 4

// Un4R transforms a curried function with 4 parameter(s) back into its original form.
func Un4R[T0, T1, T2, T3, R any](fn func(T0) func(T1) func(T2) func(T3) R) func(T0, T1, T2, T3) R {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) R {
		return fn(arg0)(arg1)(arg2)(arg3)
	}
}

// Un4 transforms a curried function with 4 parameter(s) back into its original form.
func Un4[T0, T1, T2, T3 any](fn func(T0) func(T1) func(T2) func(T3)) func(T0, T1, T2, T3) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) {
		fn(arg0)(arg1)(arg2)(arg3)
	}
}

// Un4R2 transforms a curried function with 4 parameter(s) back into its original form.
func Un4R2[T0, T1, T2, T3, R0, R1 any](fn func(T0) func(T1) func(T2) func(T3) (R0, R1)) func(T0, T1, T2, T3) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3) (R0, R1) {
		return fn(arg0)(arg1)(arg2)(arg3)
	}
}

// Un4SR transforms a curried function with 4 parameter(s) back into its original form.
func Un4SR[T0, T1, T2, T3, R any](fn func(T0) func(T1) func(T2) func(...T3) R) func(T0, T1, T2, ...T3) R {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 ...T3) R {
		return fn(arg0)(arg1)(arg2)(arg3...)
	}
}

// Un4S transforms a curried function with 4 parameter(s) back into its original form.
func Un4S[T0, T1, T2, T3 any](fn func(T0) func(T1) func(T2) func(...T3)) func(T0, T1, T2, ...T3) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 ...T3) {
		fn(arg0)(arg1)(arg2)(arg3...)
	}
}

// Un4SR2 transforms a curried function with 4 parameter(s) back into its original form.
func Un4SR2[T0, T1, T2, T3, R0, R1 any](fn func(T0) func(T1) func(T2) func(...T3) (R0, R1)) func(T0, T1, T2, ...T3) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 ...T3) (R0, R1) {
		return fn(arg0)(arg1)(arg2)(arg3...)
	}
}

// region 5

// Un5R transforms a curried function with 5 parameter(s) back into its original form.
func Un5R[T0, T1, T2, T3, T4, R any](fn func(T0) func(T1) func(T2) func(T3) func(T4) R) func(T0, T1, T2, T3, T4) R {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 T4) R {
		return fn(arg0)(arg1)(arg2)(arg3)(arg4)
	}
}

// Un5 transforms a curried function with 5 parameter(s) back into its original form.
func Un5[T0, T1, T2, T3, T4 any](fn func(T0) func(T1) func(T2) func(T3) func(T4)) func(T0, T1, T2, T3, T4) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 T4) {
		fn(arg0)(arg1)(arg2)(arg3)(arg4)
	}
}

// Un5R2 transforms a curried function with 5 parameter(s) back into its original form.
func Un5R2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0) func(T1) func(T2) func(T3) func(T4) (R0, R1)) func(T0, T1, T2, T3, T4) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 T4) (R0, R1) {
		return fn(arg0)(arg1)(arg2)(arg3)(arg4)
	}
}

// Un5SR transforms a curried function with 5 parameter(s) back into its original form.
func Un5SR[T0, T1, T2, T3, T4, R any](fn func(T0) func(T1) func(T2) func(T3) func(...T4) R) func(T0, T1, T2, T3, ...T4) R {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 ...T4) R {
		return fn(arg0)(arg1)(arg2)(arg3)(arg4...)
	}
}

// Un5S transforms a curried function with 5 parameter(s) back into its original form.
func Un5S[T0, T1, T2, T3, T4 any](fn func(T0) func(T1) func(T2) func(T3) func(...T4)) func(T0, T1, T2, T3, ...T4) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 ...T4) {
		fn(arg0)(arg1)(arg2)(arg3)(arg4...)
	}
}

// Un5SR2 transforms a curried function with 5 parameter(s) back into its original form.
func Un5SR2[T0, T1, T2, T3, T4, R0, R1 any](fn func(T0) func(T1) func(T2) func(T3) func(...T4) (R0, R1)) func(T0, T1, T2, T3, ...T4) (R0, R1) {
	return func(arg0 T0, arg1 T1, arg2 T2, arg3 T3, arg4 ...T4) (R0, R1) {
		return fn(arg0)(arg1)(arg2)(arg3)(arg4...)
	}
}
